In [1]:
import pandas as pd
from sklearn.datasets import load_iris
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("OldDataSet.csv")

In [2]:
df

Profile Pic  Nums/Length Username  Full Name Words  Bio Length  \
0               1                 0.000                2          42   
1               1                 0.067                2           0   
2               1                 0.000                0           0   
3               1                 0.000                2          14   
4               1                 0.000                2           0   
...           ...                   ...              ...         ...   
1395            0                 0.400                0           0   
1396            1                 0.143                3           0   
1397            1                 0.000                1           0   
1398            1                 0.000                1         137   
1399            0                 0.000                0           0   

      External Url  Private  Verified  Business  #Posts  #Followers  \
0                1        0         0         0     102         678   
1                0        0         0         0      58         334   
2                0        0         0         0      44         539   
3                0        0         0         0     188        3098   
4                0        0         0         1     496        1079   
...            ...      ...       ...       ...     ...         ...   
1395             0        0         0         0       0          14   
1396             0        0         0         0      20          51   
1397             0        0         0         0       2         267   
1398             0        0         0         0       9         164   
1399             0        0         0         0       1         260   

      #Following  Fake  
0            405     0  
1            434     0  
2            364     0  
3            286     0  
4           1979     0  
...          ...   ...  
1395         468     1  
1396         423     1  
1397        3555     1  
1398        4058     1  
1399        5923     1  

[1400 rows x 12 columns]

In [3]:
X=df.iloc[:, 0:11].values
X[0]

array([  1.,   0.,   2.,  42.,   1.,   0.,   0.,   0., 102., 678., 405.])

In [4]:
y=df[['Fake']]
y

Fake
0        0
1        0
2        0
3        0
4        0
...    ...
1395     1
1396     1
1397     1
1398     1
1399     1

[1400 rows x 1 columns]

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

print(len(X_train), len(y_train))
print(len(X_test), len(y_test))

938 938
462 462


In [6]:
from sklearn.svm import SVC
clf = SVC(gamma='auto')
print(clf.fit(X_train, y_train.values.ravel()))

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [7]:
print("TRAIN SET", clf.score(X_train, y_train))
print("TEST  SET", clf.score(X_test, y_test))

TRAIN SET 1.0
TEST  SET 0.5541125541125541


In [8]:
#STANDARDIZATION

In [9]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
Xtrain_Standard = scaler.transform(X_train)
Xtest_Standard = scaler.transform(X_test)

Xtrain_Standard[0]

array([ 0.30116055,  3.46340999, -1.38735742, -0.77273669, -0.53049106,
       -0.49065338, -0.34350781, -0.54202685, -0.23613877, -0.11591222,
        2.3230234 ])

In [11]:
print(clf.fit(Xtrain_Standard, y_train.values.ravel()))

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [12]:
print("TRAIN SET", clf.score(Xtrain_Standard, y_train))
print("TEST  SET", clf.score(Xtest_Standard, y_test))

TRAIN SET 0.9051172707889126
TEST  SET 0.9069264069264069


In [13]:
#NORMALIZATION

In [14]:
normalizer = preprocessing.Normalizer().fit(X_train)
normalizer

Normalizer(copy=True, norm='l2')

In [15]:
Xtrain_Normalized = normalizer.transform(X_train)
Xtest_Normalized = normalizer.transform(X_test)

Xtrain_Normalized[0]

array([1.40281976e-04, 7.01409882e-05, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.12225581e-03, 1.17836860e-02, 9.99929928e-01])

In [16]:
print(clf.fit(Xtrain_Normalized, y_train.values.ravel()))

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [17]:
print("TRAIN SET", clf.score(Xtrain_Normalized, y_train))
print("TEST  SET", clf.score(Xtest_Normalized, y_test))

TRAIN SET 0.94136460554371
TEST  SET 0.9393939393939394
